
#cloud-config

coreos:
  etcd:
    discovery: [THE URL FROM CALLING `curl -s http://discovery.etcd.io/new`]
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
  - name: etcd.service
    command: start
  - name: fleet.socket
    command: start
  - name: fleet.service
    command: start
